export const companyOverviewSchema = {
  type: "object",
  required: [
    "symbol",
    "assetType",
    "name",
    "description",
    "exchange",
    "country",
    "sector",
    "industry",
    "peRatio",
    "eps",
    "forwardPE",
  ],
  properties: {
    symbol: { type: "string" },
    assetType: { type: "string" },
    name: { type: "string" },
    description: { type: "string" },
    exchange: { type: "string" },
    country: { type: "string" },
    sector: { type: "string" },
    industry: { type: "string" },
    peRatio: { type: "string" },
    eps: { type: "string" },
    forwardPE: { type: "string" },
  },
} as const;
